stages:
  stage_01_load_split_save_data:
    cmd: python src/stage_01_load_split_save_data.py
    deps:
      - config/config.yaml
      - src/utils/all_utils.py
      - src/stage_01_load_split_save_data.py
    outs:
      - data/x_test.npy
      - data/x_train.npy
      - data/y_test.npy
      - data/y_train.npy
  
  stage_02_build_save_model:
    cmd: python src/stage_02_build_save_model.py
    deps:
      - src/stage_02_build_save_model.py
      - config/config.yaml
      - src/utils/all_utils.py
      - src/utils/models.py
      - params.yaml
    outs:
      - artifacts/untrained_models/untrained_model.h5

  stage_03_create_save_callbacks:
    cmd: python src/stage_03_create_save_callbacks.py 
    deps:
      - src/stage_03_create_save_callbacks.py 
      - config/config.yaml
      - src/utils/all_utils.py
      - src/utils/callbacks.py
    outs:
      - artifacts/callbacks/checkpoint.cb
      - artifacts/callbacks/tensorboard.cb
  
  stage_04_train:
    cmd: python src/stage_04_train.py
    deps:
      - src/stage_04_train.py
      - config/config.yaml
      - params.yaml
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - data/x_test.npy
      - data/x_train.npy
      - data/y_test.npy
      - data/y_train.npy
      - artifacts/untrained_models/untrained_model.h5
      - artifacts/callbacks/checkpoint.cb
      - artifacts/callbacks/tensorboard.cb
    outs:
      - artifacts/trained_models/trained_model.h5