base:
  num_classes: 10
  include_top: False
  image_width: 32
  image_height: 32
  image_channels: 3
  weights: imagenet
  optimizer: Adam
  epochs: 1
  batch_size: 64
  loss_fnc: sparse_categorial_crossentropy
